In [6]:
import pandas as pd
data=pd.read_csv("C:\\Users\\aarth\\Downloads\\shopping_behavior_updated (1).csv")
data.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Yes,31,PayPal,Annually

In [8]:
data.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.749949,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716223,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,50.000000,NaN,NaN

In [9]:
data.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [15]:
data.columns=data.columns.str.lower()
data.columns=data.columns.str.replace(' ','_')
data=data.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [16]:
data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'discount_applied',
       'previous_purchases', 'payment_method', 'frequency_of_purchases'],
      dtype='object')

#Create a column age_group

In [17]:
labels=['Young Adult','Adult','Middle-aged','Senior']
data['age_group']=pd.qcut(data['age'],q=4,labels=labels)

In [18]:
data[['age_group','age']].head()

     age_group  age
0  Middle-aged   55
1  Young Adult   19
2  Middle-aged   50
3  Young Adult   21
4  Middle-aged   45

Create Purchase Columns purchase_frequency_days

In [19]:
frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90}
data['purchase_frequency_days']=data['frequency_of_purchases'].map(frequency_mapping)

In [20]:
data[['purchase_frequency_days','frequency_of_purchases']].head()

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually

In [23]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\aarth\anaconda3\lib\site-packages (2.0.43)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet>=1 in c:\users\aarth\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\aarth\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [27]:
# Step 1: Connect to MySQL

from sqlalchemy import create_engine

# Replace these with your actual MySQL details
username = "root"              # default MySQL username
password = "aarthi26"     # MySQL password
host = "localhost"             # Running locally
port = "3306"                  # Default MySQL port
database = "customer_behaviour"  # Database you created in MySQL

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Step 2: Load DataFrame into MySQL

table_name = "customer"

data.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print(
    f"Data successfully loaded into table '{table_name}' "
    f"in database '{database}'."
)

Data successfully loaded into table 'customer' in database 'customer_behaviour'.